246: add firebase token verification
gtubt/gtubt-backend pull request #12
Opened 2021-04-14 11:09 UTC by alikaradogan

## What does this PR do?

* Adds firebase token verification as a middleware to the backend.

2021-04-14 15:28 UTC, onurccn requested changes

2021-04-14 15:28 UTC, onurccn commented on app/middlewares.js
> +  const firebaseToken = req.get("x-firebase-header");
Ya bu mobilde gozumden kacmis. Mobilde de header yerine token yazsak daha iyi olurdu (X-FIREBASE-TOKEN). Bir de buyuk harflerle olmasi gerekmiyo mu?

2021-04-14 15:29 UTC, onurccn commented on app/middlewares.js
> +      res.status(404).json(utils.get_response_object(null, `Unable to verify ID token. Reason: ${error}`, 404));
404 not found degil de 401 unauthorized donersek daha iyi olur

2021-04-14 23:03 UTC, alikaradogan commented on app/middlewares.js
> +  const firebaseToken = req.get("x-firebase-header");
x-firebase-token yapabiliriz.
Buyuk kucuk fark etmiyor. JS tarafinda ideal kullanim kucuk harf diyordu bir kac yerde.

2021-04-16 07:01 UTC, YasirNacak approved these changes

2021-04-17 08:33 UTC, gurolcay approved these changes

2021-04-17 08:35 UTC, merged

2021-04-17 09:06 UTC, gurolcay commented
![](https://github.trello.services/images/mini-trello-icon.png) [backend login entegrasyonu backend](https://trello.com/c/0X6jZB69/246-backend-login-entegrasyonu-backend)