249: add posts endpoint
gtubt/gtubt-backend pull request #13
Opened 2021-04-15 19:18 UTC by alikaradogan

## What does this PR do?

* Adds posts endpoint.

2021-04-16 07:02 UTC, YasirNacak approved these changes

2021-04-17 09:05 UTC, gurolcay commented
![](https://github.trello.services/images/mini-trello-icon.png) [posts endpointlerinin hazirlanmasi](https://trello.com/c/ihNgDToC/249-posts-endpointlerinin-hazirlanmasi)

2021-04-19 18:10 UTC, alikaradogan commented
![](https://github.trello.services/images/mini-trello-icon.png) [posts endpointinin news olarak guncellenmesi](https://trello.com/c/6ZwWG4lK/233-posts-endpointinin-news-olarak-guncellenmesi)

2021-04-19 18:18 UTC, alikaradogan commented
![](https://github.trello.services/images/mini-trello-icon.png) [mocha ile news backend testlerinin eklenmesi](https://trello.com/c/EIDrXsLT/237-mocha-ile-news-backend-testlerinin-eklenmesi)

2021-04-20 21:26 UTC, gurolcay requested changes

2021-04-20 21:26 UTC, gurolcay commented on test/controllers/test-news-controller.js
> +describe("GTUBT-Backend", function () {
en distaki describe'a ihtiyacimiz yok.

2021-04-20 21:26 UTC, gurolcay commented on test/controllers/test-news-controller.js
> +    describe("Create", function () {
create yerine `POST news` seklinde isimlendirme yapalim. digerleri de bunun gibi olsun

2021-04-20 21:26 UTC, gurolcay commented on test/controllers/test-news-controller.js
> +        axios
chai kullanarak istek atalim. burada ayakta bir server'a ihtiyac duyuyoruz. boyle olmamali

2021-04-20 21:26 UTC, gurolcay commented on app/models/news/news.js
> +            var d = new Date(),
asagidaki sekilde yapsak daha iyi olmaz mi?
```
var d = new Date(startDate)
var today = new Date.now()
if (today > d){
...
}
```

2021-04-20 21:26 UTC, gurolcay commented on app/models/news/news.js
> +            if (endDate < this.startDate) {
harika!

2021-04-20 21:34 UTC, alikaradogan commented on app/models/news/news.js
> +            var d = new Date(),
Olur. 👍🏻

2021-04-20 21:35 UTC, alikaradogan commented on test/controllers/test-news-controller.js
> +describe("GTUBT-Backend", function () {
Bir sonraki commit'te silinecek.

2021-04-20 21:35 UTC, gurolcay commented on test/controllers/test-news-controller.js
> +const assert = require("assert");
dosya basinda ```process.env.NODE_ENV = 'test';``` tanimlamasi yapar misin

2021-04-20 21:36 UTC, alikaradogan commented on test/controllers/test-news-controller.js
> +    describe("Create", function () {
Bir sonraki committe degisecek.

2021-04-20 21:37 UTC, alikaradogan commented on test/controllers/test-news-controller.js
> +        axios
Bir sonraki committe chai eklenecek ve testler chai'ye gore degisecek.

2021-04-28 19:46 UTC, gurolcay commented on test/controllers/test-news-controller.js
> +          console.log(err);
console.log ne icin var?

2021-04-28 19:46 UTC, gurolcay commented on test/controllers/test-news-controller.js
> +          console.error("Error: " + err.message);
error'u bu sekilde basmak yerine throw ettigimiz error icine vermemiz daha dogru olmaz mi? bilmedigim bir sey mi var?

2021-05-01 15:16 UTC, gurolcay approved these changes

2021-05-01 15:16 UTC, merged