187: New Backend
gtubt/gtubt-backend pull request #5
Opened 2021-02-21 09:04 UTC by YasirNacak

2021-02-21 19:35 UTC, gurolcay commented
index.js dosyasinda ES6'ya gore import edebiliriz require'lari

2021-02-21 19:44 UTC, gurolcay commented
datayi serialize/deserialize islemlerini bu paket ile yapamaz miyiz? veya daha iyisi?
https://www.npmjs.com/package/sequelize-serialize

2021-02-21 19:53 UTC, YasirNacak commented
@gurolcay Şu anki işlemlerimizin hangisi için gerekli bu?

2021-02-22 06:20 UTC, gurolcay commented
post edilen datanin validasyonu ve donecegimiz response icin bunu kullanmaliyiz.

2021-02-26 18:34 UTC, YasirNacak commented
> post edilen datanin validasyonu ve donecegimiz response icin bunu kullanmaliyiz. mesela create_user fonksiyonunda gelen datayi oldugu gibi almisiz. bir dogrulamadan (validation) gecirmemiz gerekli.

@gurolcay https://sequelize.org/master/manual/validations-and-constraints.html
bu sekilde validation kodu yazdim. custom validator da yazabiliyoruz student id gibi ozel fieldlar icin. Uygun mudur?

2021-02-27 14:07 UTC, gurolcay commented on migrations/20210221064347-create-user.js
> +'use strict';
neden birden fazla migration dosyamiz var? bunu teke indiremiyor muyuz?

2021-02-27 14:09 UTC, gurolcay commented
bu branchte tum backend uc noktalarini eklemeyelim, bu sadece user endpoint'i icin olsun. diger her bir uc nokta icin ayri branch olsun. 

- [ ] bu pr adi guncellenmeli
- [ ] user migration dosyalari bir tane olmali.

2021-02-27 16:55 UTC, gurolcay requested changes

2021-02-27 16:55 UTC, gurolcay commented on app/controllers/users-controller.js
> -const { User } = require("../../models");
abi bunu bilerek users klasoru altina aldim. baska bir dosyaya ihtiyac duyabiliriz. users ile alakali her seyin o klasor altinda olmasi gerekli. bunu degistirmeyelim

2021-02-27 16:55 UTC, gurolcay commented on app/routes/users/user-route-param-handler.js
> +const user_route_param_handler = async (req, res, next, value) => {
bunun adi user_route_param_handler olmamali bence. cunku bu sekilde user router'indaki her parametreyi handler ediyor gibi bir anlam cikiyor. halbuki oyle degil `user` parametresini handle ediyor sadece

2021-02-27 16:55 UTC, gurolcay commented on app/routes/users/user-route-param-handler.js
> +module.exports = user_route_param_handler;
buraya baska parametre handlerlar gelebilir. ornegin `users/:user/books/:book_id` gibi bir endpoint olursa buradaki `book_id`'yi handle edecek fonksiyon burada olmali.

2021-02-27 17:02 UTC, gurolcay requested changes

2021-02-27 17:02 UTC, gurolcay commented on app/api.js
> +api.use("/user", user_router);
cogul olmali

2021-02-27 17:02 UTC, gurolcay commented on app/controllers/users-controller.js
> +const get_user_with_email = async (req, res, next) => {
adini get_user olarak guncelleyelim

2021-02-27 17:08 UTC, gurolcay requested changes

2021-02-27 17:08 UTC, gurolcay commented on app/controllers/users-controller.js
> +  await User.findAll().then((result) => {
bunu herhangi bir query string alabilir ve ona gore filtreleyebilir sekilde mi yapsak?

2021-02-27 17:08 UTC, gurolcay commented on app/routes/users/user-route-param-handler.js
> +const user_route_param_handler = async (req, res, next, value) => {
ayrica bu dosyanin adini da cogul yapabilir miyiz?

2021-02-27 17:14 UTC, YasirNacak commented on app/controllers/users-controller.js
> -const { User } = require("../../models");
user ile ilgili tek controller var su an. genelde tercih edilen de 1 model 1 controller oldugu icin boyle birakalim

2021-02-27 17:15 UTC, YasirNacak commented on app/routes/users/user-route-param-handler.js
> +const user_route_param_handler = async (req, res, next, value) => {
su anki api designimiz bu sekilde. user modelimiz de extend olmayacak. farkli parametreler gerekirse o sekilde yapariz

2021-02-27 17:16 UTC, YasirNacak commented on app/routes/users/user-route-param-handler.js
> +module.exports = user_route_param_handler;
yukarida yazdim

2021-02-27 17:19 UTC, YasirNacak commented on app/controllers/users-controller.js
> +  await User.findAll().then((result) => {
bu endpointin app tarafinda bir kullanimi yok. ben basta debug icin eklemistim zaten. hepten silebiliriz de ama su anki haliyle birakiyorum

2021-02-27 17:19 UTC, YasirNacak commented on app/api.js
> +api.use("/user", user_router);
anlamadim burada neyin cogul olmasi gerektigini

2021-02-27 17:21 UTC, gurolcay commented on app/api.js
> +api.use("/user", user_router);
users olmali

2021-02-27 17:23 UTC, gurolcay commented on app/routes/users/user-route-param-handler.js
> +const user_route_param_handler = async (req, res, next, value) => {
ticket'lar icin yazmaya basladigimizda buna ihtiyacimiz olacak. coook sonra ihtiyac duyacagimiz bir sey degil yani simdiden yapmak varken sonraya birakmaya gerek yok :)

2021-02-27 17:23 UTC, gurolcay commented on app/routes/users/user-route-param-handler.js
> +module.exports = user_route_param_handler;
yukarida yazdim ben de :D

2021-02-27 17:25 UTC, gurolcay commented on app/controllers/users-controller.js
> +  await User.findAll().then((result) => {
ilerde admin user icin kullanabiliriz, boyle kalsin madem.

2021-02-27 17:32 UTC, gurolcay approved these changes

2021-02-27 17:35 UTC, gurolcay approved these changes

2021-02-27 17:37 UTC, merged