[WIP] 228: New Backend Ticket Endpoint
gtubt/gtubt-backend pull request #9
Opened 2021-04-04 11:19 UTC by YasirNacak

2021-04-04 13:03 UTC, onurccn commented on app/migrations/20210404102329-ticket-migration.js
> +"use strict";
Bu dosyaya ihtiyac olmamasi lazimdi aslinda. Bu migration i gondermeden denedin mi?

2021-04-17 09:07 UTC, gurolcay commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ticket endpoint](https://trello.com/c/9ZfGJiej/228-ticket-endpoint)

2021-04-25 09:58 UTC, YasirNacak commented
@gurolcay @onurccn yeni ticket modeline gore guncelleme yaptim. Ek olarak diger endpointlerde de promise donen yerleri then&catch olarak duzenledim.

2021-04-25 10:51 UTC, gurolcay commented on app/routes/events/events-route-param-handler.js
>      next();
event olmadigi halde gecise izin vermis mi oluyoruz?

2021-04-25 10:51 UTC, gurolcay commented on app/routes/tickets/tickets-route-param-handler.js
> +    next();
value dogru gelmedi halde gecise izin mi vermis olduk?

2021-04-25 10:51 UTC, gurolcay commented on app/models/tickets/ticket.js
> +    static OwnerAssociation = null;
`Owner` yerine `User` kullanalim. Model baglantisi anlaminda daha iyi olacaktir.

2021-04-25 11:04 UTC, YasirNacak commented on app/models/tickets/ticket.js
> +    static OwnerAssociation = null;
[73d27ae](https://github.com/gtubt/gtubt-backend/pull/9/commits/73d27aea2488253ac610c0b2385387fb5cb11292) ile duzelttim.

2021-04-25 11:04 UTC, YasirNacak commented on app/routes/tickets/tickets-route-param-handler.js
> +    next();
[73d27ae](https://github.com/gtubt/gtubt-backend/pull/9/commits/73d27aea2488253ac610c0b2385387fb5cb11292) ile duzelttim.

2021-04-25 11:04 UTC, YasirNacak commented on app/routes/events/events-route-param-handler.js
>      next();
[73d27ae](https://github.com/gtubt/gtubt-backend/pull/9/commits/73d27aea2488253ac610c0b2385387fb5cb11292) ile duzelttim.

2021-04-25 11:27 UTC, gurolcay requested changes

2021-04-25 11:27 UTC, gurolcay commented on app/migrations/20210404102329-ticket-migration.js
> +      owner_id: {
burasi `owner_id` olarak kalmis

2021-04-25 11:31 UTC, YasirNacak commented on app/migrations/20210404102329-ticket-migration.js
> +      owner_id: {
Bu migartion'u komple silmis olmam lazimdi. https://github.com/gtubt/gtubt-backend/pull/9#discussion_r606799039 burada @onurccn belirtmis gerek olmadigini zaten. Code first approach ile model uzerinden table uretiliyor. Dosyayi [76844b0](https://github.com/gtubt/gtubt-backend/pull/9/commits/76844b09d6ef287b3b1008493617a2f6c3087197) ile kaldirdim.

2021-04-25 11:35 UTC, gurolcay approved these changes

2021-04-25 11:36 UTC, merged